[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = [] }

async-trait = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
once_cell = "1.19"
web-sys = { version = "0.3", features = [
    "Window",
    "Navigator",
    "Serial",
    "SerialPort",
    "SerialOptions",
    "SerialPortRequestOptions",
] }
uuid = { version = "1", features = ["v4", "serde", "js"] }

project_core = { workspace = true }
ui = { workspace = true }

[features]
default = ["web"]
web = ["dioxus/web"]
