[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = [] }

uuid = { version = "1", features = ["v4", "serde"] }

project-core = { workspace = true }
ui = { workspace = true }

serialport = "4.5"
tokio = { version = "1.0", features = ["sync", "macros"] }
async-trait = "0.1"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
